package com.aijobfinder.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "job_matches")
public class JobMatch {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnore
    private User user;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "job_id", nullable = false)
    private Job job;

    private Double matchPercentage; // e.g. 94.0

    private Double skillsScore;     // 40%
    private Double experienceScore; // 20%
    private Double titleScore;      // 15%
    private Double locationScore;   // 10%
    private Double educationScore;  // 5%
    private Double projectsScore;   // 10%

    @Lob
    @Column(columnDefinition = "CLOB")
    private String matchedSkillsJson = "[]"; // ["Java", "Spring Boot", "REST API", "PostgreSQL"]

    @Lob
    @Column(columnDefinition = "CLOB")
    private String missingSkillsJson = "[]"; // ["AWS", "Docker"]

    @Lob
    @Column(columnDefinition = "CLOB")
    private String matchSummary; // Why it matches, generated by MatchingEngine or LLM

    @Lob
    @Column(columnDefinition = "CLOB")
    private String experienceSummary;

    @Lob
    @Column(columnDefinition = "CLOB")
    private String locationSummary;

    private LocalDateTime computedAt = LocalDateTime.now();

    public JobMatch() {}

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }

    public Job getJob() { return job; }
    public void setJob(Job job) { this.job = job; }

    public Double getMatchPercentage() { return matchPercentage; }
    public void setMatchPercentage(Double matchPercentage) { this.matchPercentage = matchPercentage; }

    public Double getSkillsScore() { return skillsScore; }
    public void setSkillsScore(Double skillsScore) { this.skillsScore = skillsScore; }

    public Double getExperienceScore() { return experienceScore; }
    public void setExperienceScore(Double experienceScore) { this.experienceScore = experienceScore; }

    public Double getTitleScore() { return titleScore; }
    public void setTitleScore(Double titleScore) { this.titleScore = titleScore; }

    public Double getLocationScore() { return locationScore; }
    public void setLocationScore(Double locationScore) { this.locationScore = locationScore; }

    public Double getEducationScore() { return educationScore; }
    public void setEducationScore(Double educationScore) { this.educationScore = educationScore; }

    public Double getProjectsScore() { return projectsScore; }
    public void setProjectsScore(Double projectsScore) { this.projectsScore = projectsScore; }

    public String getMatchedSkillsJson() { return matchedSkillsJson; }
    public void setMatchedSkillsJson(String matchedSkillsJson) { this.matchedSkillsJson = matchedSkillsJson; }

    public String getMissingSkillsJson() { return missingSkillsJson; }
    public void setMissingSkillsJson(String missingSkillsJson) { this.missingSkillsJson = missingSkillsJson; }

    public String getMatchSummary() { return matchSummary; }
    public void setMatchSummary(String matchSummary) { this.matchSummary = matchSummary; }

    public String getExperienceSummary() { return experienceSummary; }
    public void setExperienceSummary(String experienceSummary) { this.experienceSummary = experienceSummary; }

    public String getLocationSummary() { return locationSummary; }
    public void setLocationSummary(String locationSummary) { this.locationSummary = locationSummary; }

    public LocalDateTime getComputedAt() { return computedAt; }
    public void setComputedAt(LocalDateTime computedAt) { this.computedAt = computedAt; }
}
